
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-frontend:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Build front-end
          working_directory: ./frontend
          command: |
            set -ex
            npm i
            npm run build
      - persist_to_workspace:
          root: ./frontend
          paths:
            - build
      # - save_cache:
      #     paths: [./build]
      #     key: frontend-build     

  run-app:
    docker:
      - image: nginx
    steps:
      - attach_workspace:
          at: /tmp/
      - run:
          name: run nginx
          working_directory: /usr/share/nginx/html
          command: |
            pwd
            cp -r /tmp/build/* .
            ls -la

      
  
  # react-app:
  #   docker:
  #     - image: 349703987105.dkr.ecr.us-east-2.amazonaws.com/udemy:latest
  #       aws_auth:
  #         aws_access_key_id: AKIAVC273L6Q6BB43FY4
  #         aws_secret_access_key: $ECR_AWS_SECRET_ACCESS_KEY
  #   steps:
  #     - checkout
  #     - run:
  #         command: |
  #           docker build .

 

# Invoke jobs via workflows
workflows:
  main-workflow:
    jobs:
      - build-frontend
      - run-app:
          requires: [build-frontend]
